"""empty message

Revision ID: 9f5f17a95f77
Revises: 
Create Date: 2024-07-12 11:51:29.014337

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f5f17a95f77'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.Column('assets', sa.JSON(), nullable=True),
    sa.Column('interval', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('look_back_period', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('investment_amount', mysql.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request')
    # ### end Alembic commands ###
